# Generated by Django 5.0.1 on 2024-01-04 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userdata_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='is_admin',
        ),
    ]
