# Generated by Django 5.0.1 on 2024-01-11 11:07

import django.contrib.postgres.indexes
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_search_vector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['date_modified']},
        ),
        migrations.AddField(
            model_name='note',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user'], name='notes_note_user_id_2efe7b_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='notes_note_search__2ae846_gin'),
        ),
    ]
